version: "3"
services:

  ############# External services

  memcached:
    image: memcached:1.4.38

  mongodb:
    # Use WiredTiger in all environments, just like at edx.org
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    image: mongo:3.0.14
    volumes:
      - ./data/mongodb:/data/db

  mysql:
    image: mysql:5.6.36
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "openedx"
      MYSQL_USER: "openedx"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/mysql:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      args:
          lms_host: openedx.com
          cms_host: studio.openedx.com
    #restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./data/edxapp:/openedx/data:ro
    depends_on:
      - lms

  rabbitmq:
    image: rabbitmq:3.6.10
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  # Simple SMTP server
  smtp:
    image: namshi/smtp
    environment:
      PORT: 9025

  ############# LMS and CMS

  lms:
    build:
      context: ./edxapp
      args:
        lms_host: openedx.com
        cms_host: studio.openedx.com
        service_variant: lms
        secret_key: "Jahpai7shahx0Ecu0nag6uiph"
    #restart: on-failure
    volumes:
      - ./data/edxapp:/openedx/data
      - ./edxapp/config/envs:/openedx/edx-platform/lms/envs
    depends_on:
      - memcached
      - mongodb
      - mysql
      - rabbitmq
      - smtp

  cms:
    build:
      context: ./edxapp
      args:
        lms_host: openedx.com
        cms_host: studio.openedx.com
        service_variant: cms
        secret_key: "Jahpai7shahx0Ecu0nag6uiph"
    #restart: on-failure
    volumes:
      - ./data/edxapp:/openedx/data
    depends_on:
      - lms

  ############# LMS and CMS workers

  # TODO one service per queue?
  lms_worker:
    build:
      context: ./edxapp
      args:
        lms_host: openedx.com
        cms_host: studio.openedx.com
        service_variant: lms
        secret_key: "Jahpai7shahx0Ecu0nag6uiph"
    command: ./manage.py lms --settings=production celery worker --loglevel=info --hostname=edx.lms.core.default.%%h --maxtasksperchild 100
    environment:
      C_FORCE_ROOT: "1" # run celery tasks as root #nofear
    #restart: on-failure
    volumes:
      - ./data/edxapp:/openedx/data
    depends_on:
      - lms

  insights:
    build: ins/

#  pipeline:
#    build: edx-analytics-pipeline/
#    command: start-hadoop.sh
##    ports:
##     - "9001:9000"
#  dataapi:
#    build: edx-analytics-data-api/
#    command: /opt/edx-analytics-data-api/manage.py runserver 0.0.0.0:8000
##    links:
##     - pipeline
##    ports:
##     - "8000:8000"
#  dashboard:
#    build: edx-analytics-dashboard/
#    command: /opt/edx-analytics-dashboard/manage.py runserver 0.0.0.0:9000
#    volumes:
#      - ./dashboard-settings:/opt/edx-analytics-dashboard/analytics_dashboard/settings
##    links:
##     - dataapi
##     - mysql
##    ports:
##     - "9000:9000"
